sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew createIliModelsXml versionTxt buildDockerImage
  - docker images

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew pushDockerImages -i
    on:
      branch: master


