sudo: required

language: java

services:
  - docker

branches:
  only:
    - master
    - stable

install: true

script:
  - ./gradlew clean createIliModelsXml
  - ./gradlew versionTxt
  - ./gradlew buildDockerImage

