name: CI/CD

on: [push]

jobs:
  build:
    env:
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}} 
      BUILD_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew createIliModelsXml addXslDeclaration validateIliModelsXml versionTxt buildDockerImage startDockerContainer checkInterlisRepository stopDockerContainer 
        #run: ./gradlew createIliModelsXml addXslDeclaration validateIliModelsXml versionTxt buildDockerImage startDockerContainer stopDockerContainer 
      - name: Push docker image
        run: ./gradlew pushDockerImages -i
        if: ${{ github.ref == 'refs/heads/master' }}  
